### ISSUE TITLE
Error when updating gems

### ISSUE THREAD

**Issue by ioannisstavrakakis** [lostisland/faraday-patron#4]
I get the following error:

`ERROR:  Error installing faraday-patron:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/patron-0.13.3/ext/patron
C:/Ruby30-x64/bin/ruby.exe -I C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0 -r ./siteconf20220105-8992-idta85.rb extconf.rb
checking for curl-config... no
checking for -lcurl... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby30-x64/bin/$(RUBY_BASE_NAME)
        --with-curl-dir
        --without-curl-dir
        --with-curl-include
        --without-curl-include=${curl-dir}/include
        --with-curl-lib
        --without-curl-lib=${curl-dir}/lib
        --with-curl-config
        --without-curl-config
        --with-curllib
        --without-curllib
extconf.rb:10:in `<main>':   Can't find libcurl or curl/curl.h (RuntimeError)

  Try passing --with-curl-config, --with-curl-dir, or --with-curl-lib and --with-curl-include
  options to extconf.

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Ruby30-x64/lib/ruby/gems/3.0.0/extensions/x64-mingw32/3.0.0/patron-0.13.3/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/patron-0.13.3 for inspection.
Results logged to C:/Ruby30-x64/lib/ruby/gems/3.0.0/extensions/x64-mingw32/3.0.0/patron-0.13.3/gem_make.out
Updating installed gems
Updating faraday-patron
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
Gems updated: patron
`

The mkmf.log reads:

` C:/Ruby30-x64/lib/ruby/gems/3.0.0/extensions/x64-mingw32/3.0.0/patron-0.13.3/mkmf.log
find_executable: checking for curl-config... -------------------- no

--------------------

have_library: checking for -lcurl... -------------------- no

"gcc -o conftest.exe -IC:/Ruby30-x64/include/ruby-3.0.0/x64-mingw32 -IC:/Ruby30-x64/include/ruby-3.0.0/ruby/backward -IC:/Ruby30-x64/include/ruby-3.0.0 -I. -D__USE_MINGW_ANSI_STDIO=1 -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0600 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64  -O3 -fno-fast-math -fstack-protector-strong conftest.c  -L. -LC:/Ruby30-x64/lib -L. -pipe -s -fstack-protector-strong  -m64   -lx64-msvcrt-ruby300  -lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi  "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <winsock2.h>
4: #include <windows.h>
5: int main(int argc, char **argv)
6: {
7:   return !!argv[argc];
8: }
/* end */

"gcc -o conftest.exe -IC:/Ruby30-x64/include/ruby-3.0.0/x64-mingw32 -IC:/Ruby30-x64/include/ruby-3.0.0/ruby/backward -IC:/Ruby30-x64/include/ruby-3.0.0 -I. -D__USE_MINGW_ANSI_STDIO=1 -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0600 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64  -O3 -fno-fast-math -fstack-protector-strong conftest.c  -L. -LC:/Ruby30-x64/lib -L. -pipe -s -fstack-protector-strong  -m64   -lx64-msvcrt-ruby300 -lcurl  -lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi  "
C:/Ruby30-x64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lcurl
collect2.exe: error: ld returned 1 exit status
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <winsock2.h>
 4: #include <windows.h>
 5: 
 6: /*top*/
 7: extern int t(void);
 8: int main(int argc, char **argv)
 9: {
10:   if (argc > 1000000) {
11:     int (* volatile tp)(void)=(int (*)(void))&t;
12:     printf("%d", (*tp)());
13:   }
14: 
15:   return !!argv[argc];
16: }
17: 
18: int t(void) { ; return 0; }
/* end */

--------------------`

Every time I run `gem update`, I have the same error. Anyway to fix it?
Thank you in advance!

**Comment by olleolleolle** [comment]
This is probably explained in the Patron gem's README, but it's about "you don't have the libcurl library where Ruby expects it to be". libcurl is the C library that offers cURL capability to Patron. See https://github.com/toland/patron for more.

**Comment by ioannisstavrakakis** [comment]
I am in Windows, and there is no such gem I can install.

**Comment by ioannisstavrakakis** [comment]
Ok thank you!

**Comment by jcowhigjr** [comment]
This might help someone who is surprised by this upgrade.

I am using an omniauth gem that depends on faraday which today bumped from 1.8 to 1.9. 

 This bumped faraday-patron from 1.0 to 2.0 

faraday-patron 2.0 changed **patron** from a dev dependency to an actual dependency.  

Patron installed fine on osx likely because i had the dependency already ..
but in my ruby-3-slim and ruby-3.1-slim (bullseye) containers it would not compile.

This could be solved in two ways add to your  Gemfile 
 faraday-patron, '~> 1.0'

Another solution is to add the build dependency to your image something like libcurl-dev

for me:

 apt-get install libcurl4-openssl-dev

allowed me to compile patron and stay up to date.

**Comment by ioannisstavrakakis** [comment]
There is no libcurl4-openssl-dev gem I can install. And I don;t know how to add faraday-patron, '~> 1.0' to my gemfile. So I think I am going to leave everything as is.

**Comment by joelsgp** [comment]
on Ruby 2.7 with msys2 I did `pacman -Syu mingw-w64-x86_64-curl` in the msys shell and that solved the issue.
